#!/usr/bin/env bash
set -eu
trap exit INT

MPK=$1
LOCALIP=$2
PORT=$3
if [ ! -f ${MPK} ]; then
	echo "Can't find any .mpk file to mobile"
	exit 1
fi
mindcli-serve ${MPK} &
sleep 1
echo "Please enter http://$LOCALIP:$PORT at Skill Store > Scan QR code > Test Skill in the HEXA App."

while :
do
	sleep 1
done
