#!/usr/bin/env bash
set -eu

pack_business() {
	# Validate manifest.json
	SKILLID=`cat manifest.json | jq -r ".skillID"`
	VERSION=`cat manifest.json | jq -r ".version"`
	if [ "${SKILLID}" == "null" ]; then
		echo "skillID in manifest.json can not be empty"
		exit 1
	fi
	if [ "${VERSION}" == "null" ]; then
		echo "version in manifest.json can not be empty"
		exit 1
	fi
	zip -r -qq /tmp/skill.mpk manifest.json remote/ robot/skill robot/deps robot/assets robot/deps 
	cp -f /tmp/skill.mpk .
	if [ -n "${MIND_USER}" ]; then
		chown ${MIND_USER}:${MIND_USER} skill.mpk 
	fi
}

pack_skill() {
	if [ -e manifest.json ] && [ -e robot/skill ] && [ -e remote ]; then
		pack_business
	else
		echo "No skill to pack. Build first."
		mindcli-build
		echo "Build succ, pack the skill."
		pack_business
	fi
}

pack_skill