#!/usr/bin/env bash
set -eu
NO_INSTALL=$1
MPK=$2
LOCAL_IP=$3
HEXA_IP=$4
if [ ! -f ${MPK} ]; then
	echo "Can't find any .mpk file to run"
	exit 1
fi
mindcli-serve ${MPK} &
mindcli-remote ${HEXA_IP} &
sleep 1
mindcli-ws ${LOCAL_IP} ${HEXA_IP} ${NO_INSTALL}
