#!/usr/bin/env bash
set -eu
if [ -e manifest.json ] && [ -e robot/skill ]; then
	# Validate manifest.json
	SKILLID=`cat manifest.json | jq -r ".skillID"`
	VERSION=`cat manifest.json | jq -r ".version"`
	if [ "${SKILLID}" == "null" ]; then
		echo "skillID in manifest.json can not be empty"
		exit 1
	fi
	if [ "${VERSION}" == "null" ]; then
		echo "version in manifest.json can not be empty"
		exit 1
	fi
	zip -r -qq /tmp/skill.mpk manifest.json remote/ robot/skill robot/deps robot/assets robot/deps 
	cp -f /tmp/skill.mpk .
	if [ -n "${MIND_USER}" ]; then
		chown ${MIND_USER}:${MIND_USER} skill.mpk 
	fi
else
	echo "No skill to pack. Did you build it yet?"
fi
